### PR TITLE
Release of 3.0.0

### PR DESCRIPTION
**Pull request by bvillanueva-mdsol**
Bring develop to master

@kenyamat @lschreck-mdsol 
Please merge if it is ok.
Thanks

FYI
@cabbott

### CODE REVIEW

**Comment by cabbott** [comment]
Excited by a 2.0 release :+1: :dancers:

**Comment by kenyamat** [comment]
I'd like to change one configuration. Please hold this PR.

**Comment by lschreck-mdsol** [comment]
@bvillanueva-mdsol @kenyamat It seems that we never released ZipkinTracerModule 2.0.0

Is it OK for me to send a commit to the develop branch which will set the version number to 2.0.0 (instead of 3.0.0) and merge this (#78) pull request to the master and release the current changes as 2.0.0? I think it is unnecessary to merge this PR and create another one just for the 3.0.0 version.

What do you think?

**Comment by kenyamat** [comment]
I've already pushed 2.0.0 to nuget.org for the task in current sprint. So we need to use 3.0.0.

**Comment by lschreck-mdsol** [comment]
In that case I think we need to close this PR and skip the version 2.0.0 on GitHub as it already has my changes for the 3.0.0.

**Comment by lschreck-mdsol** [comment]
Or better, let's just rename this PR and merge it as 3.0.0!

**Pull request merged**
